name: azkar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.14+14
environment:
  sdk: ">=3.0.0  <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.2
  geolocator: ^9.0.2
  hijri: ^3.0.0
  flutter_qiblah: ^2.0.2
  dio: ^5.2.0+1
  shimmer: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons:    ^1.0.2
  intl:
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.1
  step_progress_indicator: ^1.0.2
  permission_handler: ^11.1.0
  flutter_timezone: ^1.0.7
  assets_audio_player: ^3.1.1
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  webview_flutter: ^4.10.0
  home_widget: ^0.7.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  share_plus: ^12.0.2
  in_app_review: ^2.0.12
  new_version_plus: ^0.0.12

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/arabic.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  json_annotation:
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1




flutter:
  uses-material-design: true
  assets:

    - assets/images/
    - assets/data/
    - assets/surat/
    - assets/music/
    - assets/db/
    - assets/convertdate.html
  fonts:
    - family: ArbFONTS
      fonts:
        - asset: assets/fonts/ArbFONTS-Droid-Arabic-Kufi.ttf
          weight: 500


   
    
   

